.TH "C:/Projetos/LinguagemProgramacao/aula.c" 3 "Tue Oct 27 2020" "Aula 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projetos/LinguagemProgramacao/aula.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Programa que não sei o quê\&.\&.\&.\&. "
.ti -1c
.RI "int \fBsoma\fP (int x, int y)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
your name (you@domain.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2020-10-27
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Programa que não sei o quê\&.\&.\&.\&. 
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SS "int soma (int x, int y)"

.PP
\fBParameters\fP
.RS 4
\fIx\fP 
.br
\fIy\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Aula 1 from the source code\&.
